src/app/person-appearance/person-appearance.component.html, src/app/person-appearance/person-appearance.component.ts
Per Signes request of which fields should go where
=> Adjust source page fields

package-lock.json, src/app/life-course/life-course-item.component.html, src/app/life-course/life-course-item.component.ts, src/app/person-appearance/person-appearance-item.component.html, src/app/person-appearance/person-appearance-item.component.ts
- Use correct data in source cards.
- Minior styling.
=> Correct fields in results

src/app/life-course/life-course-item.component.html, src/app/person-appearance/person-appearance-item.component.html, src/assets/styling/source-card.scss
- Use a before element for color indicator.
=> Source card responsive styling

src/app/search/simple/search-simple.component.html, src/app/search/simple/search-simple.component.ts, src/index.html
Gets text for frontpage from config.
=> Fields from config

src/app/person-appearance/person-appearance.component.html, src/app/person-appearance/person-appearance.component.ts, src/app/search/search.service.ts
- fjernet navn i header
- fixet permalink i ID
- tilføjet last_update info
=> Source view, opdateringer baseret på feedback 1

src/app/elasticsearch/elasticsearch.service.ts, src/app/form-elements/dropdown/component.ts, src/app/form-elements/dropdown/view.html, src/app/search-result-list/search-result-list.component.ts, src/app/search/simple/search-simple.component.html, src/app/search/simple/search-simple.component.ts, src/assets/styling/button.scss, src/assets/styling/dropdown.scss, src/index.html
Update dropdowns to support
- categories
- disabled entries
- focus changing as navigating up and down
- scrolling when dropdown gets too long
Also adds support for searching for the new fields we have added.
=> Dropdown (fixes baseret på feedback 1)

src/app/life-course/life-course-item.component.html, src/assets/styling/source-card.scss
=> Fix birth date icon alignment

src/app/life-course/life-course-item.component.html, src/app/person-appearance/person-appearance-item.component.html, src/app/search-result-list/search-result-list.component.html, src/app/search-result-list/search-result-list.component.ts, src/assets/styling/results-header.scss, src/assets/styling/source-card.scss
- Changes to search result header.
- Changes to result-items.
=> Correct responsive styling according to design

src/app/life-course/life-course.component.html, src/app/person-appearance/person-appearance.component.html
Also removed the icon as per Signes request.
=> Add back button to source pages

src/assets/styling/search-intro.scss
=> The neat alignment went missing when I made the frontpage responsive

src/app/display-helpers.ts, src/app/life-course/life-course-item.component.ts, src/app/life-course/life-course.component.ts, src/app/person-appearance/person-appearance-item.component.ts, src/app/person-appearance/person-appearance.component.ts
Corrected labels (sogn, herred, amt) on source locations.
Extracted methods for making pretty birth and source locations
=> Parish district county labels

src/app/life-course/life-course.component.html, src/app/life-course/life-course.component.ts, src/app/person-appearance/person-appearance.component.html, src/app/person-appearance/person-appearance.component.ts, src/app/search-history.ts
- Use latest search-history to navigate back to search results from source pages.
=> Link back to search results v2

src/assets/styling/_variables.scss, src/assets/styling/boolean.scss, src/assets/styling/button.scss, src/assets/styling/dropdown.scss, src/assets/styling/input-group.scss, src/assets/styling/loading-spinner.scss, src/assets/styling/pagination.scss, src/assets/styling/search-history-sidebar.scss, src/assets/styling/search-intro.scss, src/assets/styling/sidebar.scss, src/assets/styling/tab.scss
- Rename black variable to off-black.
- Use this as the font and border color
=> Off-black color for text and borders

src/app/elasticsearch/elasticsearch.service.ts, src/app/person-appearance/person-appearance-resolver.service.ts, src/app/person-appearance/source-data.component.html, src/app/person-appearance/source-data.component.ts, src/app/search/search.service.ts
Now that we have `institution` name in sources index and `pa_entry_permalink` on pas, we can properly link directly to original sources (or show error messages)
=> Make institution link work

src/app/elasticsearch/elasticsearch.service.ts, src/app/life-course/life-course.component.html, src/app/person-appearance/person-appearance-item.component.html, src/app/person-appearance/person-appearance-item.component.ts
Also fixes issue with the lifecourse resolver
=> Title for truncnated names

src/app/elasticsearch/elasticsearch.service.ts, src/app/life-course/life-course.component.html, src/app/life-course/life-course.component.ts, src/assets/styling/source-graph.scss
- Add info icon to tooltip when hovering a link
- Add better (danish) descriptions of methods
- Add long descriptions as titles when hovering
=> Better descriptions for linking methods

src/app/search-result-list/search-result-list.component.html, src/app/search-result-list/search-result-list.component.ts, src/assets/styling/search-modifiers.scss
Support for picking number of items on a page
Look at that scrollbar!
Also responsive:
=> Choose number of items per page

src/app/life-course/life-course.component.html, src/app/person-appearance/person-appearance-item.component.html, src/app/person-appearance/person-appearance.component.html, src/app/search-result-list/search-result-list.component.html, src/app/search/simple/search-simple.component.html, src/assets/styling/data-page-header.scss, src/assets/styling/results-header.scss, src/assets/styling/search-intro.scss, src/assets/styling/search-modifiers.scss
- Responsive stuff:
-- Search results
-- Source data page
-- Landing page
=> Responsive markup/design changes

src/app/display-helpers.ts, src/app/elasticsearch/elasticsearch.service.ts, src/app/filter-sidebar/component.ts, src/app/filter-sidebar/view.html, src/app/person-appearance/person-appearance-item.component.ts, src/app/search-result-list/search-result-list.component.html, src/app/search-result-list/search-result-list.component.ts, src/app/search-result-list/search-result-resolver.service.ts, src/app/search/search.service.ts
WIP: jeg har lavet koden til at få det rigtige aggregate ud, men den kan ikke køre fordi event_type i Elasticsearch er type text i stedet for keyword, så vi kan ikke aggregere på den. Derfor kan jeg ikke komme videre lige nu.
Update 2020-12-11: nu ikke længere WIP
=> Filtrering af kilder skal understøtte begravelser

src/app/search-history/component.html, src/app/search-history/component.ts
Use helper functions to show the correct data for burials in search history sidebar.
=> Correct burial data in search history sidebar

src/app/search/search-routing.module.ts
=> Remove /search/simple from index url

src/app/life-course/life-course.component.html, src/app/person-appearance/person-appearance.component.html, src/app/search-result-list/search-result-list.component.html, src/assets/styling/results-header.scss
- Add link to frontpage on search results.
- Change text on links to search results
=> Add link to frontpage on search results. 

src/app/person-appearance/source-data.component.html, src/assets/styling/_variables.scss, src/assets/styling/data-page-data-section.scss, src/assets/styling/dropdown.scss, src/assets/styling/info-box.scss, src/assets/styling/pagination.scss, src/assets/styling/source-card.scss, src/assets/styling/source-graph.scss, src/assets/styling/tab.scss
- Cleanup CSS -> Add whitespace and such.
- Align our colors. Use the variables where it makes sense.
- Change `grey-border` color variables to a better looking one from the design.
- BEMify `data-page-data-section` scss.
=> Align colors with variables

src/app/search-result-list/search-result-list.component.html, src/app/search-result-list/search-result-list.component.ts, src/app/search/simple/search-simple.component.html, src/app/search/simple/search-simple.component.ts, src/assets/styling/dropdown.scss, src/assets/styling/results-header.scss, src/assets/styling/search-options.scss
- Add clear button to search results.
- Add clear button to simple search (frontpage).
=> Add "Clear search" buttons

src/app/search/simple/search-simple.component.html, src/assets/styling/button.scss, src/assets/styling/search-options.scss
=> Add mobile UI optimizations regarding search options

src/app/search-result-list/search-result-list.component.html, src/app/search-result-list/search-result-list.component.ts, src/assets/styling/pagination.scss
- Cap max pages so it fits the limit in elasticsearch
- Remove direct link to "max page" in pagination -- also to first page for consistency
- Add possibility to jump 10 pages backwards or forwards instead
=> Pagination with many pages fix

src/app/elasticsearch/elasticsearch.service.ts
Per Signes request, we run with 0 fuzziness for now.
=> Disable fuzziness for now

src/app/elasticsearch/elasticsearch.service.ts, src/app/life-course/life-course-resolver.service.ts, src/app/person-appearance/person-appearance-resolver.service.ts, src/app/search-history.ts, src/app/search-result-list/search-result-list.component.html, src/app/search/search.service.ts, src/app/search/simple/search-simple.component.html, src/assets/styling/boolean.scss, src/assets/styling/button.scss, src/assets/styling/data-page-header.scss, src/assets/styling/dropdown.scss, src/assets/styling/icon.scss, src/assets/styling/input-group.scss, src/assets/styling/results-header.scss, src/assets/styling/search-options.scss
Various code cleanup things, see commit messages :smile:
=> Code cleanup

src/app/display-helpers.ts, src/app/person-appearance/source-data.component.ts, src/app/search/search.service.ts
Use the new source_type_wp4 field to determine which fields should be shown in the person_appearence page.
=> Use source type to determine pa fields

src/app/person-appearance/person-appearance-item.component.ts, src/app/person-appearance/source-data.component.html, src/app/person-appearance/source-data.component.ts, src/assets/styling/_variables.scss, src/assets/styling/card.scss, src/assets/styling/source-card.scss
burials and deaths from Kirkebøger should have the color black, burials from Begravelsesprotokol should stay gray
=> burials and deaths from Kirkebøger should have the color black

src/app/search-result-list/search-result-list.component.html, src/app/search-result-list/search-result-list.component.ts, src/assets/styling/_variables.scss, src/assets/styling/button.scss, src/assets/styling/card.scss, src/assets/styling/data-page-footer.scss, src/assets/styling/filter-sidebar.scss
Update filter-chip look and add information about which filterCategory the filter belongs to.
=> Update filter-chip look

package-lock.json, package.json, src/app/auth/auth0.component.ts, src/app/elasticsearch/elasticsearch.service.ts, src/app/link-rating/component.html, src/app/link-rating/component.ts, src/assets/styling/modal.scss, src/environments/environment.dev-remote-api.ts, src/environments/environment.prod.ts, src/styles.scss
The Elastic Search service is now morphed into the API service.
Some calls are still not implemented in the API, so we have hardcoded elastic search api url.
I think naming became a bit messy, if you got any ideas, please let me know :)
=> Get link rating options using the API

src/app/user-profile/user-profile.component.html
If user has a firstname and lastname we try to show that. 
Otherwise we show their nickname.
=> User-page: If user has a firstname and lastname we try to show that. 

src/app/elasticsearch/elasticsearch.service.ts
Now links are always included in the lifecouse
=> remove unused elastic search method 'searchLinks'

src/app/elasticsearch/elasticsearch.service.ts, src/app/filter-sidebar/component.ts, src/app/search-result-list/search-result-resolver.service.ts, src/app/search/search.service.ts
use birthyear_searchable and source_year_searchable fields for filters.
We are waiting for the new index of ES for this change to be merged.
=> use birthyear_searchable and source_year_searchable fields for filters

src/app/auth/auth-button/component.ts, src/app/auth/auth.service.js, src/app/auth/util.ts, src/app/link-rating/component.ts
Forgot to push the last changes made on add-auth-redirect
=> Add auth redirect - latest commits

src/app/elasticsearch/elasticsearch.service.ts, src/app/person-appearance/person-appearance-resolver.service.ts, src/app/person-appearance/source-data.component.ts, src/app/search-history/component.html, src/app/search/search.service.ts
- Source data is part of the personAppearance data
- PersonAppearance endpoint now only returns pa without all the elastic search meta data.
=> Update personAppearance API data

src/app/person-appearance/person-appearance.component.ts
trying to trigger a build on test / staging
=> remove trailing newline

src/app/auth/auth-button/component.html, src/app/auth/auth-button/component.ts, src/app/auth/util.ts, src/app/user-profile/user-profile.component.ts, src/environments/environment.dev-remote-api.ts, src/environments/environment.prod.ts, src/environments/environment.staging.ts
after logout you return to baseUrl / homepage. This will probably change when moving the login button, but now we just ensure that we keep within the linklive search page when logging out.
Did refactor the logout to make it easier to expand later on.
=> Logout return to 'homepage'

src/app/app.module.ts, src/app/life-course/life-course.component.html, src/app/life-course/life-course.component.ts, src/app/person-appearance/person-appearance-item.component.html, src/assets/styling/life-course-page.scss, src/environments/environment.prod.ts
Fixes that some links cannot be hovered.
Right now there is a known issue with stacking where link lines are on top of some tooltips. This turns out to not be trivial to fix due to technicalities of Angular and SVGs... Might have to redo the entire graph in HTML, which is a bit harder to reason about 😦 but that's for later. This fixes the main issues.
=> Links svg fixes

src/app/link-rating/component.html, src/assets/styling/loading-spinner.scss, src/assets/styling/modal.scss, src/assets/styling/overlay.scss, src/assets/styling/sidebar.scss
Fixes issue where modal would grow in height to exceed page size, so some content was unreadable.
=> Rating modal fix

src/assets/styling/button.scss, src/assets/styling/source-card.scss
Based on/merges into #230 
Before
After
=> Button sizing

src/app/search-result-list/search-result-resolver.service.ts, src/app/search-term-values.ts, src/app/search/simple/search-simple.component.html, src/app/search/simple/search-simple.component.ts, src/assets/styling/info-box.scss, src/assets/styling/search-intro.scss, src/assets/styling/utility.scss
The layout is done.
WIP: add the last of the hardcoded fields - needs mapping all the way into search.
Trello card: https://trello.com/c/jv6KzKK4/235-implementering-af-ny-s%C3%B8geforside
Sketch reference: https://www.sketch.com/s/7b9ae46e-4815-4d61-9577-46584e81114b/a/rbWrz3K
=> New search start page

src/app/life-course/life-course.component.html, src/assets/styling/life-course-page.scss, src/assets/styling/utility.scss
Trello: https://trello.com/c/yvFB9VoV/239-overskrift-og-link-over-speghettidiagram
Toggl: `Overskrift og link over speghettidiagram`
- Add title and link that explains the link section on the lifecourse page.
=> Add link title and explainer link to lifecourse-page

src/assets/styling/life-course-page.scss
Simple stuff. We will make a effort to show the linking graph on tablet/mobile views later.
=> Only show linking graph on desktop

src/app/filter-sidebar/view.html, src/app/search-history/component.html, src/assets/styling/sidebar.scss
- Add a new modifier to sidebar: Sticky header.
- Use sticky header sidebar for the search history and the filter sidebar.
- Update text in the close/save button to be more clear.
=> Update filter menu: Sticky header and new button text

src/app/life-course/source-linking-graph.component.ts
=> Add guard in totalratings data, because the array can be null now.

src/app/elasticsearch/elasticsearch.service.ts
WIP: based on #244 
In pas index in elasticsearch, the values are no longer nested inside person_appearance
we can't test this right now as staging API isn't taking into account queries, so this is WIP for now
=> Search in both person appearance and top-level

src/app/app.module.ts, src/app/user-management/service.ts, src/app/user-profile/user-profile.component.html, src/app/user-profile/user-profile.component.ts, src/assets/styling/utility.scss
=> Edit profile

src/app/person-appearance/person-appearance-resolver.service.ts, src/app/search/search.service.ts
(It moved from hh_id to standard.household_id.)
=> Fix household/related people linking by using the correct field

src/app/elasticsearch/elasticsearch.service.ts, src/app/life-course/life-course.component.html, src/app/life-course/life-course.component.ts, src/app/life-course/source-linking-graph.component.html, src/app/link-rating/component.html, src/app/link-rating/component.ts
WIP because based on #244 - merge after that.
=> Ratings no duplicate

src/app/elasticsearch/elasticsearch.service.ts, src/app/filter-sidebar/component.ts, src/app/person-appearance/source-data.component.ts, src/app/search-history/component.ts, src/app/search-result-list/search-result-list.component.ts, src/app/search-result-list/search-result-resolver.service.ts, src/app/search/search.service.ts, src/app/util/display-helpers.ts, src/assets/styling/source-card.scss
Running through a list of all valid values for `event_type` to ensure we are supporting them. Investigation led to some cleanup.
=> Support all event types

src/app/app.module.ts, src/app/modal/component.html, src/app/modal/component.ts, src/app/user-management/service.ts, src/app/user-profile/user-profile.component.html, src/app/user-profile/user-profile.component.ts
Instead of editing nickname.
Also some minor optimizations.
=> Edit username on my-page

src/app/data/data.service.ts, src/app/search-result-list/search-result-resolver.service.ts, src/app/search-term-values.ts, src/app/search/search.service.ts
Trello: Tilføj ervherv som søgefelt
=> Make occupation searchable

src/app/person-appearance/person-appearance-resolver.service.ts, src/app/search/search.service.ts
WIP because we currently cannot test this as the field is null for all non-census event types
=> Group related people on new pa_grouping_id_wp4 field

src/app/person-appearance/person-appearance.component.html, src/app/search-term-values.ts
Trello task: https://trello.com/c/SikeOpaW/299-s%C3%B8gning-p%C3%A5-personregistrerings-id-virker-ikke
Toggl label: `Søgning på personregistrerings ID virker ikke`
=> Search for pa key instead of pa_id

src/app/analytics.module.ts
Fix typo `track`->`send`. Oops.
=> Fix tracking script

src/app/search/simple/search-simple.component.html, src/assets/styling/search-intro.scss, src/assets/styling/utility.scss
Trello: https://trello.com/c/NWkZSUsT/339-mindre-designrettelser-lavet-af-mads
- Add minor styling changes as requested in this file: https://github.com/CopenhagenCityArchives/linklives-wordpress-theme/blob/master/wordpress/wp-content/themes/linklives/resources/assets/styles/layouts/_ll-search.scss
=> Minor styling changes from Mads the designer

src/app/life-course/life-course.component.html
Trello: https://trello.com/c/pKZg8v9B/143-som-bruger-vil-jeg-gerne-se-at-et-livsforl%C3%B8b-ikke-l%C3%A6ngere-er-gyldigt
=> Add 'back to frontpage' link to historic lifecourse modal

src/app/life-course/source-linking-graph.component.html, src/assets/styling/source-graph.scss
Trello: https://trello.com/c/l7dwd895/352-%C3%A6ndring-af-tekst
- Update text.
- Update positioning because text is longer now.
=> Update text and positioning for duplicated link warning

src/app/data/data.service.ts, src/app/filter-sidebar/component.ts, src/app/life-course/life-course-item.component.html, src/app/search-result-list/search-result-list.component.ts, src/app/search/search.service.ts, src/app/util/display-helpers.ts
Trello: https://trello.com/c/kyLLBYtB/356-fjern-filtret-kilde%C3%A5r-der-er-identisk-med-h%C3%A6ndelses%C3%A5r
- Remove source year (kildeår) from filter.
- Clean up after removal of source year.
- Close SVG tag correctly. VS code did not like it the other way, and I obey.
=> Remove source year from filter

src/lls-login-button.js
=> Deduplicate login button (2)

src/app/search-result-list/search-result-list.component.html
Total sources for Downlaod restrictions: Pa hit + Lifecouse hits.
=> Calculate total sources for "estimated_hits" in the search component

src/app/download-data-link/view.html
=> Show numbers related to download criteria in download-modal

src/app/data/data.service.ts, src/app/data/download.service.ts, src/app/download-data-link/component.ts, src/app/search-result-list/search-result-list.component.html, src/app/search-result-list/search-result-list.component.ts, src/app/search-result-list/search-result-resolver.service.ts
Wires up downloading of search results.
(Currently the backend is blocked, but you can download empty CSV or XLSX files here.)
=> Download search results

src/app/download-data-link/component.ts, src/app/download-data-link/view.html
=> Update download promt content

src/app/data/download.service.ts, src/app/download-data-link/component.ts
Toggl: `Hvis man har mere en 1000 resultater hente kun de første 1000`
=> Allow download data over 1000 posts

src/app/app.module.ts
Toggl: Authentication fejl på personregistreringssider
=> Fix authentication issue with person appearance page not working when not logged in

src/app/data/data.service.ts, src/app/data/download.service.ts, src/app/person-appearance/person-appearance-resolver.service.ts, src/app/person-appearance/person-appearance.component.html, src/app/person-appearance/related-people.component.ts
- new get endpoint includes related persons
- new download endpoint includes related persons tab in xlsx
=> Person appearance v2 endpoints

src/app/app.component.ts, src/app/data/download.service.ts, src/app/download-data-link/view.html, src/app/loading-overlay/view.html, src/assets/styling/loading-spinner.scss, src/assets/styling/overlay.scss
Because some downloads take ~1 minute we now show our trusty loading indicator when downloading.
I cleaned up the use of loading indicators and overlays a bit to make it easy to add.
=> Loading indicator on download
