src/app/person-appearance/person-appearance-resolver.service.ts

A hh_id is unique only inside a source_id, so we matched too broadly!

Match households with source_id, too

---

src/app/search-result-list/search-result-list.component.html
src/app/search-term-values.ts

Jf. feedback fra arkivet er der nu rettet til i hvilke felter der søges på.
Virker ikke lige nu, da _sortable felterne mangler i indexet. Det arbejder Bo på

Sortering på korrekte felter

---

src/app/search-result-list/search-result-list.component.html
src/assets/styling/boolean.scss
src/assets/styling/button.scss
src/assets/styling/search-modifiers.scss

From Signe:
> Fire småting til looket.
>- Stregen omkring 'kilder' er tyndere end sorter-boksen. Jeg tænker de skal have samme tykkelse (som sorter efter).
>- Skriften Filtrer resultater - samme størrelse/højde som sorter efter (måske størrelsen er den samme, men det bare er højden, der snyder.
>- Skriften inde i de grå valgte filtre bokse må gerne være en smule større.
>- Jeg tror der skal stå FT 1850, FT 1880 osv. Bare med tanke for når der kommer flere kilder.

Filter menu minor changes

---

src/app/elasticsearch/elasticsearch.service.ts
src/app/search-result-list/search-result-list.component.ts
src/app/search-result-list/search-result-resolver.service.ts
src/app/search-term-values.ts

Jeg har implementeret det så lifecourses boostes en lille smule over kilder, og bruger en basisscore lig med den mest relevante kilde i livsforløbet.
Så for den mest relevante kilde viser vi først livsforløb, derefter kilderne, og ligeledes for den næst-mest-relevante kilde, osv.
Konkret:
- lifecourses får score efter "max" score på en person_appearance under den (default er "avg" der resulterede i at lifecourses altid blev vist længere nede på listen)
- score for lifecourses ganges med 1.05 (fordi nestede resultater pr default devalues en lille smule, så lifecourses altid var efter kilder; det vender vi om på denne måde)

Sort by relevance

---

src/app/person-appearance/person-appearance-resolver.service.ts
src/app/person-appearance/person-appearance.component.html
src/app/person-appearance/related-people.component.ts

For burials, we still tried to look up household-related people, but none exist (no hh_id), which resulted in an error in elasticsearch.
Now, we don't do that, and also hide the "Related people" tab for burials.

Bugfix allow view burials

---

src/app/search-result-list/search-result-list.component.html
src/app/search-result-list/search-result-list.component.ts
src/assets/styling/pagination.scss

- makes pagination numbers have thousand separators like proper big Danish numbers (easier to read)
- makes pagination item boxes grow with the number, so the number always fits inside the box

Pagination detail fixing

---

src/app/elasticsearch/elasticsearch.service.ts
src/app/search-result-list/search-result-resolver.service.ts
src/app/search/simple/search-simple.component.ts

- When searching from frontpage using the simple query, auto-check both indexes
- When no index is checked, return an empty search result

Select indexes logic

---

src/app/search-history/component.html
src/app/search-result-list/search-result-resolver.service.ts
src/app/search-term-values.ts

Currently we do not save index query param in the search history. This means that the search history links basically always shows no results (because no sources/index is chosen).
This is a quick fix. We should show the index param in the search history markup as well, but for now its hidden.
Merging quickly to fix the bug, but feel free to review and lets stabilize this thing :).

Add index query params to search history.

---

src/app/app.component.ts
src/app/life-course/life-course-item.component.ts
src/app/life-course/life-course.component.html
src/app/life-course/life-course.component.ts
src/app/person-appearance/person-appearance-item.component.ts
src/app/person-appearance/person-appearance.component.ts
src/app/person-appearance/related-people.component.html
src/app/search-result-list/search-result-list.component.html
src/app/search-result-list/search-result-list.component.scss
src/app/search-result-list/search-result-list.component.ts
src/app/search/search.component.ts
src/app/search/simple/search-simple.component.html
src/app/search/simple/search-simple.component.scss
src/app/search/simple/search-simple.component.ts
src/assets/styling/_variables.scss
src/assets/styling/dropdown.scss
src/assets/styling/filter-sidebar.scss
src/assets/styling/info-box.scss
src/assets/styling/input-group.scss
src/assets/styling/search-options.scss
src/assets/styling/sidebar.scss
src/styles.scss

- Extract styling from search-simple and make it global.
- Info-box is now more reuseable and scales to full width on mobile devices.
- Remove unused scss files because we use global CSS.
- Clean input-group CSS.
- Cleanup in dropdown CSS.
- Use our utility classes to add spacing in PA item lists instead of `mx-2` which is from the wordpress styling.

Extract style tags and cleanup

---

src/app/search-history.ts
src/app/search-history/component.html
src/app/search-history/component.ts
src/app/search-result-list/search-result-resolver.service.ts

Remove index from queryParams.
Add index as a part of a SearchHistory entry instead

Cleanup Search History index query params

---

src/assets/styling/button.scss

- Add border to all button types. This makes it easier to align them since their heights are the same and such.
- Cleanup CSS.
- Change padding slightly to align height with inputs.
- Font size is now 16px and not 13px.

Align button height with inputs

---

src/app/life-course/life-course.component.html
src/app/life-course/life-course.component.ts
src/app/search-history/component.html

- Use display helpers on lifecourse page. These basically does all the work for us.
- Use the same helpers in the search history. Lifecourse entries with burials had the same problems where names and birthlocations where not show.
- Add death year to lifecourse page (if we have it).

Display correct burial data on lifecourses

---

src/app/search-history.ts
src/app/search-history/component.ts
src/app/search-result-list/search-result-list.component.ts

Changes:
- Joined arrays with "," when adding index as a queryParam. If index is an array the queryParams inserts it multiple times (ala `index=pas,index=lifecourses` instead of `index=pas,lifecourses`).
- Fix issue where the checkboxes where not checked off when using the links in search history.

Fix bugs in index params

---

src/app/search-term-values.ts

- Add "fritekst" (query) as an option in the "add field" dropdown for advanced search.
- Create "other" category that fritekst belongs in.
Trello:
https://trello.com/c/QeIp0XnF/92-mulighed-for-at-tilf%C3%B8je-friteksts%C3%B8gning-i-felterne-i-det-bl%C3%A5-b%C3%A5nd-%C3%B8verst-i-s%C3%B8geresultatvisning

Add query field as an option in advanced search

---

src/app/life-course/life-course.component.html
src/app/life-course/life-course.component.ts
src/app/person-appearance/person-appearance-item.component.html
src/app/person-appearance/person-appearance-item.component.ts
src/app/person-appearance/person-appearance.component.html
src/app/person-appearance/person-appearance.component.ts
src/app/person-appearance/related-people.component.html
src/app/person-appearance/related-people.component.ts
src/app/person-appearance/source-data.component.ts
src/assets/styling/data-page-data-section.scss
src/assets/styling/data-page-footer.scss
src/assets/styling/icon.scss
src/assets/styling/source-card.scss
src/index.html

- Omdøb "relaterede personer" til "husstand" for folketællinger
- Fremhæv den kilde man allerede er på under "relaterede personer"
- Sorter husstandens medlemmer efter transkriptions-ID
- Lange værdier ombrydes i flere linjer
- "Om livsforløb" text at end of lifecourses editable via config

Census sources updates 20210210

---

src/app/filter-sidebar/view.html
src/app/search-result-list/search-result-list.component.html

- Make all buttons inside the sidebar tabindex -1 when the sidebar is not open.
- Hide "current chosen filters" section when there is no chosen filters.

Make hidden elements not tabbable in search result header

---

src/app/filter-sidebar/component.ts
src/app/filter-sidebar/view.html
src/app/search-history/component.html
src/app/search-history/component.ts

- Close sidebar when the overlay is clicked.
- Close sidebar when the escape key is pressed.
Note:
I have no clue if the keyup listeners are a good way to to this. Its pretty simple though :sweat_smile:.

Better sidebar dismissing

---

src/app/search-history.ts
src/app/search-history/component.ts
src/app/search-result-list/search-result-list.component.html
src/app/search-result-list/search-result-list.component.ts
src/app/search-result-list/search-result-resolver.service.ts

- Tilføjer kildefilter, sideinfo (antal, sidenummer) og sorteringsinfo til søgehistorik-entries for søgeresultater
- Linker korrekt tilbage til søgeresultatsiden
- Fixer edge case hvor man kunne ende på tomme sider ved at filtrere efter at være gået til en senere side

Når man går tilbage til søgeresultatside fra søgehistorik, skal den huske siden man var på

---

src/app/elasticsearch/elasticsearch.service.ts
src/app/filter-sidebar/component.ts

The number of sources in a source bucket should not vary by source buckets picked. So we make 2 requests now, one to get source buckets, and another to get results. The source bucket request gets no results so is quite small in terms of data transfer (< 1 kb).
Additionally, this PR ensures that we update available buckets every time a search is changed (before, it only happened when the source bucket sidebar was created).

Improved source bucket aggregation

---

src/app/elasticsearch/elasticsearch.service.ts

Note: merges into #99.
Adds support for wildcards `?` (any one single character) and `*` (zero or more of any characters) in search queries.

Wildcard search

---

src/app/elasticsearch/elasticsearch.service.ts
src/app/search-result-list/search-result-list.component.ts

Arrow down now results in urls with sortOrder=asc EXCEPT for relevance, where it is sortOrder=desc; and vice versa.
This means that both the sort order button works as expected, and the url says what is actually going on.

Move logic of flipping sort order to results list, so the URL says what we are actually doing

---

src/app/search-history.ts
src/app/search-history/component.ts
src/app/search-result-list/search-result-list.component.ts
src/app/search-result-list/search-result-resolver.service.ts

- When navigating to /results without any valid search query params, users are now redirected back to the frontpage
- Instead of `page` we now call the query parameter for pagination `pg` so we don't trip up Wordpress (resulting in page 404s when linking to results pages).

Results page fixes

---

src/app/elasticsearch/elasticsearch.service.ts

max_expansions defaults to 50, 250 allows matches on e.g. Aalborg->Ålborg
also default operator is OR but we want AND, so if you include several names in last name, you only get results that match all of them

Enable fuzziness on `match` queries, increase fuzz expansions so we hit more cases!

---

src/app/search-result-list/search-result-list.component.html
src/app/search-result-list/search-result-list.component.ts
src/app/search/simple/search-simple.component.html
src/app/search/simple/search-simple.component.ts

When adding a new field (frontpage, results page) focus that element
setTimeout waits for template to re-render before we try to focus, so the element can be rendered first :-)

Focus new fields

---

src/app/elasticsearch/elasticsearch.service.ts
src/app/search-history.ts
src/app/search-history/component.ts
src/app/search-result-list/search-result-resolver.service.ts

(Right now, the _fz fields in the db do not include the values in the non-_fz fields in the db, so this ensures fuzzy always gets *more* results.)
Early out on exact keys, instead of having them as a trailing check.

Rewrite search key code so we always include default, and then *add* the mode key

---

src/app/elasticsearch/elasticsearch.service.ts

Based on #121 
Uafklaret: skal denne merges as-is, for den virker ikke vildt godt sådan som indekset er sat op lige nu?
Derudover: skal den også virke for fritekstsøgning og søgninger med wildcards? F.eks. ved også at splitte wildcard søgninger op i flere queries hvis ikke der er quotes omkring dem
E.g. `"J?ns N?els"` bliver til én wildcard søgning, men `J?ns N?els` bliver til to, én på `J?ns` og én på `N?ls`.
Og lignende for fritekstsøgninger: skal vi trække ting i quotes ud? Kan vi overhovedet det med simple_query_string?

Phrase search

---

src/app/person-appearance/person-appearance-resolver.service.ts
src/app/search/search.service.ts

Pr have fields event_id and event_persons to indicate related person_appearances.
right now I have simply modified the code in the person appearance a bit to store the related persons in the hh field.
At some point we should maybe rename the hh field, as this is more of a 'all kind of related persons field' than a 'hh/ household' field.

Adds related pas for source type PR / Kirkebog

---

src/app/elasticsearch/elasticsearch.service.ts

remove fuzziness param from elastic search query now we have decided not to use the built-in elastic-search fuzzy functionality.
Instead we have made fields for fuzzy search that we can make regular searches on.
Having the fuzzy param made searches on integers fail (namely search on source_year

Remove fuzziness param from elastic search query

---

package-lock.json
package.json
src/app/display-helpers.ts
src/app/elasticsearch/elasticsearch.service.ts
src/app/filter-sidebar/component.ts
src/app/filter-sidebar/view.html
src/app/search-history.ts
src/app/search-history/component.ts
src/app/search-result-list/search-result-list.component.html
src/app/search-result-list/search-result-list.component.ts
src/app/search-result-list/search-result-resolver.service.ts
src/app/search/search.service.ts

Now we can both filter on sources and on events.
When choosing multiple filteroptions from same filter type, it should act like 'or clauses' (broadening the search) 
When choosing filteroptions across filter types, it should act like 'and clauses' (narrowing the search)
The implementation is very naive, and styling and refactoring should be done in next PR.

Adds Source filter options

---

src/app/elasticsearch/elasticsearch.service.ts

Uafklaret - afventer afklaring af hvorfor elasticsearch ikke kan håndtere de nye queries hvor `fields` ikke er `["*"]`.

Draft: Specify fields on fritekst query based on mode

---

src/app/elasticsearch/elasticsearch.service.ts
src/environments/environment.dev-remote-api.ts
src/environments/environment.prod.ts

Update apiUrl
update call to search endpoint
update call to get pa
update call to get lifecource
Should sources and links still be fetched in seperate calls or should these be included in the lifecourse call?

use api to search elastic search

---

src/app/elasticsearch/elasticsearch.service.ts

the API uses elastic search *_search* endpoint instead of *_doc* endpoint when getting the personAppearance. Therefore the response is an elasticSearchResult.
The response of this endpoint will change in next week to include the source data and to remove the elastic search meta-data

get personAppearance endpoint return elastic search _search result 

---

src/app/app-routing.module.ts
src/app/elasticsearch/elasticsearch.service.ts
src/app/life-course/life-course-item.component.html
src/app/life-course/life-course-item.component.ts
src/app/life-course/life-course-resolver.service.ts
src/app/life-course/life-course.component.html
src/app/life-course/life-course.component.ts
src/app/person-appearance/person-appearance.component.html
src/app/search-history.ts
src/app/search-history/component.html
src/app/search-result-list/search-result-list.component.html
src/app/search/search.service.ts

**Toggl**: Man kan ikke klikke på personregistrering og se oplysninger fra kilden om personen - API endpoint get /LifeCourse/{key} opdatering af data  
**Trello**: [Man kan ikke klikke på personregistrering og se oplysninger fra kilden om personen - API endpoint get /LifeCourse/{key} opdatering af](https://trello.com/c/BQw7xIrw/181-man-kan-ikke-klikke-p%C3%A5-personregistrering-og-se-oplysninger-fra-kilden-om-personen-api-endpoint-get-lifecourse-key-opdatering-af)
- Use lifecourse key as identifier for lifecourses instead of the id.  
- Get lifecourses using the API instead of directly from elastic search.  
- Get lifecouse endpoint is including the links in the lifecourse, therefore we dont need to get theese after getting the lifecourse
-

Get lifecourses by key through api

---

src/app/app.module.ts
src/app/elasticsearch/elasticsearch.service.ts
src/app/user-profile/user-profile.component.html
src/app/user-profile/user-profile.component.ts

**toggle**: Vis livsforløb en bruger har ratet  
**trello**: [Som bruger vil jeg gerne kune se en oversigt over hvilke livsforløb jeg har ratet link på](https://trello.com/c/9wrg6f5U/196-som-bruger-vil-jeg-gerne-kune-se-en-oversigt-over-hvilke-livsforl%C3%B8b-jeg-har-ratet-link-p%C3%A5)
- endpoint to get lifecourses with links that have been rated
- on user profile page the list of lifecourses is shown in the same manner as search results
- http interceptor added for this endpoint to ensure authorization

Show rated lifecourses

---

src/app/search/simple/search-simple.component.html
src/assets/styling/results-header.scss
src/assets/styling/search-options.scss

Since the text changed from "kilde" to "personregistrering" our UI has been shown to be unable to deal with longer strings. 
**Fix:** They are now beneath each other to avoid problems if the label text gets too long.
Not the most elegant solution, but a more robust one.

Visual fix on results-type checkboxes on search result page.

---

src/app/elasticsearch/elasticsearch.service.ts

**Før:**
Der er 11 søgeresultater = 4 livsforløb + 7 personregisteringer
I Filtret er der blevet talt:
4 livsforløb med 2 kilder hver = 8 personregisteringer.
7 personregisteringer + 8 personregisteringer fra livsforløb
= 15 resultater.
Forslået løsning:
Jeg opdatere filtret til kun at tælle personregisteringer

filter should only show number of person appearances.

---

src/assets/styling/life-course-page.scss
src/assets/styling/source-card.scss

Button text breaking into two lines because of too much text.
Decrease padding and button text size on tablet. Other devices should not be affected by these changes.

Fix Search result items' CTA labels on tablet

---

src/app/elasticsearch/elasticsearch.service.ts
src/app/search-result-list/search-result-list.component.ts

Trello: https://trello.com/c/e0tbqobQ/169-s%C3%B8geresultat-antal-opdeles-p%C3%A5-livsforl%C3%B8b-og-personregistreringer
Also avoid everything blowing up, if a number is falsy :)

Show amount of pas and lifecourses instead of total hits

---

src/app/search-history/component.ts
src/app/search-result-list/search-result-list.component.ts

When searching for literally nothing (e.g. all search fields empty) the search history would end up with an entry with no query - and when trying to go back to this entry, chaos would ensue. Searching without a single search parameter results in errors, and no search fields rendered. Instead, we now force an empty "Fritekst" field for entries with no other query fields.
Trello: Nogle gange fejler 'tilbage til søgeresultat' på livsforløb

Pagination edge case fix

---

src/app/search-history.ts

(for the edge case where people search for empty string)

When getting latest search query, ensure at least one search param

---

src/app/elasticsearch/elasticsearch.service.ts

Optimizes the calls initiated every time we search, so we do a single call for all aggregations, instead of one per bucket type.

Optimize search calls

---

src/assets/styling/dropdown.scss

The line height had been changed to 1.5 per default, which resulted in dropdowns becoming larger, because of sizing of current item in the dropdown. Fixing this to 1 realigns the sizes of the dropdowns and button. Especially visible as the height of the sort order button and sort field dropdown were misaligned
Before:
After:

Fix alignment of sizes of sorting dropdowns with size of "Alle filtre" button

---

src/app/life-course/life-course-item.component.ts
src/app/life-course/life-course.component.ts

In life courses, the list of person appearances is in some cases sorting-independent and in other cases requires sorting chronologically by event year.
This PR replaces the implementation where the sorting happened on every execution of a getter (quite often!) with implementations that limit the sorting to happen on load.

Ensure desctructive sort is only called once

---

src/app/search-result-list/search-result-list.component.ts
src/assets/styling/results-header.scss

When searching for only lifecourses only show lifecourse counts, not pa counts; and vice versa.

Result count text: only show counts for result types we search for

---

src/app/life-course/life-course-item.component.html

Trello: https://trello.com/c/bppDyN3f/228-personregistreringer-%C3%A6ndres-til-kilder-i-bl%C3%A5-bokse-i-s%C3%B8geresultat
Toggl: `Personregistreringer ændres til Kilder i blå bokse i søgeresultat`
- Change "personregisteringer" to "kilder".

Change subtitle text on lifecourse source card

---

src/app/life-course/life-course.component.html
src/app/person-appearance/person-appearance.component.html
src/assets/styling/button.scss
src/assets/styling/data-page-header.scss
src/assets/styling/source-card.scss

Trello: https://trello.com/c/9F3y3Jh5/241-knap-design-p%C3%A5-s%C3%B8gehistorik
Toggl: `Knap design på søgehistorik`
- Change search history link to a button look.
- Also remove Min from the button text
Nb: Haven't done much to improve the mobile view. I feel like we need to reconsider the "back-link" and "back-to-lifecourse" link.

Change search history link to a button look. 

---

src/app/life-course/life-course-item.component.html
src/app/person-appearance/person-appearance-item.component.html
src/assets/styling/source-card.scss

Trello: https://trello.com/c/HlmUUQG2/237-designjustering-p%C3%A5-s%C3%B8geresultat
Toggl: `Designjustering på søgeresultat`
- Update UI as per Signes request.
- The "person-data" section has 5% more width and the header section 5% less.
We could make more for the important data by shrinking the CTA section. I will reach out to signe and ask if this is something we want.
The changes makes the lifecourse interface with links very bad on smaller screens, and we should fix it. I think a quickfix could be to remove the link-graph on tablet size.

Tweak source card UI size

---

src/app/life-course/life-course.component.html
src/assets/styling/life-course-page.scss
src/assets/styling/utility.scss

Based on #236 - adds the new layout of lifecourse ID to the lifecourse page.

Lifecourse id update

---

src/app/elasticsearch/elasticsearch.service.ts
src/app/life-course/life-course.component.html
src/app/life-course/source-linking-graph.component.html
src/app/life-course/source-linking-graph.component.ts
src/assets/styling/link.scss
src/assets/styling/source-graph.scss
src/assets/styling/utility.scss

Trello: https://trello.com/c/L6ngCzVG/238-nyt-design-og-tekst-p%C3%A5-bl%C3%A5-link-boks
Toggl: `Nyt design og tekst på blå link boks`
- Change text and tweak markup in source-graph-link tooltip.
- Set "totalRatings" variable when a link is hovered, since we need to show the number of ratings in the tooltip.
The height of the tooltip had to be increased, and therefore the "pointy"-arrow is no longer centered on the "link-circle". I did not want to try to recalculate the top position that is in the frontend, since @hypesystem can figure it out instantly.

Update source graph tooltip

---

src/app/life-course/life-course.component.html

There were some problems with the text on medium and smaller screens.

Add spacing to about lifecourse text

---

src/app/search-result-list/search-result-resolver.service.ts

Basically makes reading filter info from query more robust, so middle values can contain `_` characters as happens for source_type_display == "Kirkebog"

Fix kirkebog filter

---

src/app/elasticsearch/elasticsearch.service.ts
src/app/life-course/source-linking-graph.component.html
src/app/life-course/source-linking-graph.component.ts
src/assets/styling/source-graph.scss

Trello: https://trello.com/c/AYvEIYuN/244-links-der-skal-have-brugernes-opm%C3%A6rksomhed
Toggl label: `Links der skal have brugernes opmærksomhed`
- Add `duplicates` to Link type (its in the data we get from the API.
- If link.duplicates is above 0, then we highlight the link with red and add descriptive text.
- Tweak the positioning of the tooltip if duplicates is true, because of the extra paragraph.

Links with duplicates

---

src/app/life-course/source-linking-graph.component.html
src/assets/styling/source-graph.scss

Trello task: https://trello.com/c/OKVyNppF/291-farve-p%C3%A5-links-cirkler-er-forsvundet-fra-prod-til-test
Toggl label:
> Farve på links cirkler er forsvundet fra prod til test

Fix source graph event colors

---

src/app/data/data.service.ts
src/app/search-history.ts
src/app/search-result-list/search-result-list.component.html
src/app/search-result-list/search-result-list.component.ts
src/app/search-result-list/search-result-resolver.service.ts
src/app/search/search.service.ts
src/app/search/simple/search-simple.component.html
src/app/search/simple/search-simple.component.ts

Adds checkbox default-true for including dubious links (where duplicates > 1). If the check mark is removed, we add the `excludeDubiousLinks=true` query param to searches. This then results in a "must not have links.duplicates greater than 1" addition to the query.
Also added it to the search history, so that should work.

Exclude dubious links

---

src/app/search-term-values.ts

Trello task: https://trello.com/c/SikeOpaW/299-s%C3%B8gning-p%C3%A5-personregistrerings-id-virker-ikke
Toggl label: `Søgning på personregistrerings ID virker ikke`
For some reason the `pa_id` is not unique in the current dataset. I find up to 4-5 of the same PA when searching for an ID.
Also the field `id` that we were searching for before, is always `0`. Weird, but I guess its just a mistake.

Person Apperance ID is called pa_id now. Also the one shown in the UI.

---

src/app/data/data.service.ts
src/app/data/rating.service.ts
src/app/life-course/life-course-resolver.service.ts
src/app/life-course/life-course.component.html
src/app/life-course/life-course.component.ts
src/app/life-course/source-linking-graph.component.html
src/app/life-course/source-linking-graph.component.ts
src/app/link-rating/component.ts

The API has changed for `GET Link/:id/Rating{/stats,}` so these endpoints now use the link ID rather than the key (cf. [swagger](https://api-test.link-lives.dk/swagger/index.html)).
I have tried to make that clear in the code + cleaned up a bit on the way.

Use id in linkrating api

---

src/app/data/data.service.ts
src/app/life-course/source-linking-graph.component.ts
src/app/search-history.ts
src/app/search-result-list/search-result-list.component.html
src/app/search-result-list/search-result-list.component.ts
src/app/search-result-list/search-result-resolver.service.ts
src/app/search/search.service.ts
src/app/search/simple/search-simple.component.html
src/app/search/simple/search-simple.component.ts

- Added ability to exclude safe links (with duplicates = 1)
- Fixed bug in source linking graph that would show links as bad even if they had duplicates = 1 (because 1 is truthy)

Search unsafe links (round 2)

---

src/app/data/data.service.ts
src/app/life-course/source-linking-graph.component.ts

Due to changes in the API the linking method always showed up as "Anden metode". This fixes the interface to what's in the API now, so we can show the information correctly again.

Show linking method

---

src/app/search-result-list/search-result-list.component.ts

We should allow at most 1000 items to be shown, as thats the limit from elasticsearch

Adjust max number of pages shown

---

src/app/search-history.ts
src/app/search-history/component.ts

At some point we must have renamed from sourceFilter to filters (whcih is more accurate!) but we still use sourceFilter in many other places in the code... defs a cleanup point at some point...

Fix some inconsistent naming of the filters on a search history entry

---

src/app/life-course/source-linking-graph.component.html
src/app/life-course/source-linking-graph.component.ts

Trello: https://trello.com/c/wD7H6gFz/154-hvis-et-link-har-f%C3%A5et-5-negative-bed%C3%B8mmelser-skal-brugerne-ikke-l%C3%A6ngere-sp%C3%B8rges-om-feedback
- Add ratingScoreStatus data to links in `source-linking-graph.component`. 
- Status can be negative or positive, depending on the amount of good/bad ratings.
- We disable rating if a link is rated too bad/good.

Add ratingScoreStatus to links

---

src/app/search-result-list/search-result-list.component.html
src/app/search/simple/search-simple.component.html
src/app/user-profile/user-profile.component.html
src/lls-login-button.js

Trello: https://trello.com/c/D35LGcNn/361-wcag-krav-inpult-felter-skal-have-beskrivelse
Did some updating to the markup to fix this issue:
> Input field has no description
1.3.1 Info and Relationships
Input fields should always have a description that is explicitly associated with the field to make sure that users of assistive technologies will also know what the field is for.
If the input field has a visible description indicating the purpose of the field, this description should be explicitly associated to the input field either as a HTML label or using the WAI-ARIA attribute 'aria-labelledby'.

Update input markup to have explicit labels with aria-labledby to be WCAG compliant

---

src/app/life-course/life-course.component.html
src/app/life-course/life-course.component.ts

c.f. "Visning af oplysninger om livsforløb" på Trello
Dette retter til så der kun bruges information fra seneste person appearance på et livsforløb til alle felter der hives op i toppen af siden.

Life course info fix

---

babel.config.js
src/lls-login-button.js

When building prod or staging disable the login button script on certain pages to avoid duplicate login button on test page

Deduplicate login button

---

babel.config.js
src/lls-login-button.js

A fix to what was done in #320: Fix env var passing: can only pass in strings.

Deduplicate login button (2)

---

src/app/life-course/life-course-item.component.ts

Same change as in #319 but fixes it for life course items (as shown in search results) for consistency.

Fix birthPlace and birthYear in life course item components too

---

src/app/user-management/service.ts
src/lls-login-button.js

This fixes the issue where the logout button would be present for longer than a login session lasts, so it looks like a user is logged in while the session has actually expired in Auth0.
On page change we check if the session has expired (24 hours) and change state if so.

Session expiry

---

src/app/download-data-link/view.html
src/assets/styling/data-page-header.scss

This approach should be a little more robust, when handling different amounts of links. The flex-wrapping works pretty alright with the 2 to 4 links that we have right now.
I think this section in general should be rethought. Maybe as a more header-like component, that can collapse or have drop-downs on mobile. 
Production:
After tweak:

Tweak Data page header links

---

src/app/data/download.service.ts
src/app/download-data-link/component.ts

I saw that we have all the data needed in the query param data.
Last restriction we needed on the download option.
Trello: https://trello.com/c/VS9OKLwW/370-som-arkivar-vil-jeg-gerne-begr%C3%A6nse-hvilke-data-der-kan-downloades

Restrict download if query params is not 2 or more.

---

src/assets/styling/data-page-data-section.scss

Make the table data more readable, and less prone to overflow errors on small devices

Make the table data more readable on small devices

---

src/app/person-appearance/source-data.component.html

Use shorthand `if/else` instead of `&&`.
Angular threw errors when returning `false` in the `[class]`.

Fix bug: Dynamic class cannot be false
